### ISSUE TITLE
Kovan token balances no longer work

### ISSUE THREAD

**Issue by SteveHoggNZ** [TrustWallet/trust-ray#352]
The kovan API used to show balances, now it always returns a zero balance e.g.

https://kovan.trustwalletapp.com/tokens?showBalance=true&address=0x2F2e0224e19A688c1FCd6128eAaCf9107e95d8C2

But the address has BLABS tokens:

https://kovan.etherscan.io/token/0xa390dd0ff6128a5c3454df097c57cdea5576063a?a=0x2F2e0224e19A688c1FCd6128eAaCf9107e95d8C2

**Comment by kolya182** [comment]
@SteveHoggNZ Hi Steve, we have disabled  https://github.com/TrustWallet/trust-ray/commit/2f552acb021832d9d15e487c8cfc29b703e7f506 tokens balances due to high call volume. We are in the process of migrating to new infrastructure, once we did we will turn in back on. But for now, you need to query balance on your own.

**Comment by SteveHoggNZ** [comment]
OK, thank you.
